### ISSUE TITLE
修改了ffmpeg_decoder.cpp中的代码，怎么编译让其生效

### ISSUE THREAD

**Issue by zhangsong1234** [BabitMF/bmf#100]
在ffmpeg_decoder中增加了部分参数设置，使用build_ffmpeg.sh未能生效

**Comment by HuHeng** [comment]
使用build.sh编译bmf源码即可，ffmpeg_decoder最终会链接到libbuiltin_modules.so动态库里

**Comment by zhangsong1234** [comment]
> 使用build.sh编译bmf源码即可，ffmpeg_decoder最终会链接到libbuiltin_modules.so动态库里

这个在官网提供的docker里修改再编译有效果，如果再自己的docker中，直接拉取主干代码，修改了ffmpeg_decoder.cpp后，重新./build.sh就会出现上面出的不生效问题

**Comment by HuHeng** [comment]
可能是没有拷贝到正确的目录里？注意一下环境变量和module加载的路径。
调试环境是不是加载的不是build目录下的库，而是上层output目录的库，需要拷贝到上层output目录里？

**Comment by zhangsong1234** [comment]
> 可能是没有拷贝到正确的目录里？注意一下环境变量和module加载的路径。 调试环境是不是加载的不是build目录下的库，而是上层output目录的库，需要拷贝到上层output目录里？

拷贝到上层的output，可以编译出新的libbuiltin_modules.so库，但在用demo中的face_detect 样例运行时，没有使用新编译的库，demo中的样例是链接的哪里的库？没找到

**Comment by HuHeng** [comment]
可以查看一下python环境中bmf模块所处目录，搜索一下目录内的库是否是你所用新版本的库。
```
import bmf
print(bmf.__file__)
```
同时关注一下PYTHONPATH环境变量。
这些可以帮助确认程序运行时所指向的库。

**Comment by zhangsong1234** [comment]
> 可以查看一下python环境中bmf模块所处目录，搜索一下目录内的库是否是你所用新版本的库。
> 
> ```
> import bmf
> print(bmf.__file__)
> ```
> 
> 同时关注一下PYTHONPATH环境变量。 这些可以帮助确认程序运行时所指向的库。

在脚本里添加"hwaccel": "cuda",但实际使用的是cpu
在trt_face_detect.py中 inference()里print(vf.frame())显示的是Frame(cpu, kUInt8, PixelFormat(12), (3, 1080, 1920))，导致后面转reformat(rgb)时报错：Unsupport PixelInfo。
Source "imgproc.cpp", line 0, in hmp::img::infer_ppixel_format(hmp::PixelInfo const&)
#0    Object "/home/dan/zs/ai-bmf/bmf-bb/output/bmf/lib/libhmp.so.1", at 0x7f353434036f, in hmp::logging::dump_stack_trace(int)
[2024-02-02 09:50:52.127] [error] node id:1 catch exception: RuntimeError: require false at /home/dan/zs/ai-bmf/bmf-bb/bmf/hml/src/imgproc/imgproc.cpp:155, Unsupport PixelInfo

At:
  /home/dan/zs/ai-bmf/bmf-bb/bmf/demo/face_detect/trt_face_detect.py(209): inference
  /home/dan/zs/ai-bmf/bmf-bb/bmf/demo/face_detect/trt_face_detect.py(255): process

**Comment by HuHeng** [comment]
确认nvcodec环境是正常的吗？
可以使用ffmpeg 测试一下nvcodec的编解码功能，确认gpu解码是正常工作的。

**Comment by zhangsong1234** [comment]
> 确认nvcodec环境是正常的吗？ 可以使用ffmpeg 测试一下nvcodec的编解码功能，确认gpu解码是正常工作的。
使用下面命令行，可以正常用gpu解码
ffmpeg -hwaccel cuvid -c:v h264_cuvid -stream_loop -1 -i test.mp4 -f null -

**Comment by zhangsong1234** [comment]
> 确认nvcodec环境是正常的吗？ 可以使用ffmpeg 测试一下nvcodec的编解码功能，确认gpu解码是正常工作的。

使用下面命令行，可以正常用gpu解码
ffmpeg -hwaccel cuvid -c:v h264_cuvid -stream_loop -1 -i test.mp4 -f null -
