### ISSUE TITLE
项目C++单测中的使用的一些素材文件去哪里下载呢？

### ISSUE THREAD

**Issue by leizh007** [BabitMF/bmf#103]
比如：

`bmf/engine/c_engine/test/test_graph.cpp`

中用到的

```
../../files/graph_dyn.json
../../files/dynamic_add.json
../../files/dynamic_remove.json
```

这些文件在项目下没有搜到呢

**Comment by sfeiwong** [comment]
https://github.com/BabitMF/bmf/releases/download/files/files.tar.gz

**Comment by leizh007** [comment]
收到了，感谢
[https://github.com/BabitMF/bmf/releases/download/files/files.tar.gz](下载地址)
