### ISSUE TITLE
请问BMF移动端上效果如何

### ISSUE THREAD

**Issue by wingsZz** [BabitMF/bmf#104]
请问BMF有支持移动端的硬解和GPU加速吗，有在移动端上做适配吗

**Comment by sfeiwong** [comment]
目前支持在android下运行硬解。后续3个月后预计会有更全面的移动端方案发布。
具体适配的场景是什么？

**Comment by wingsZz** [comment]
打算在ios、android以及鸿蒙下使用这个框架做一些视频处理相关的东西

> 目前支持在android下运行硬解。后续3个月后预计会有更全面的移动端方案发布。 具体适配的场景是什么？

**Comment by sfeiwong** [comment]
除了ios、android一些实现，BMF也有在鸿蒙下的适配计划。 这个需求是在library层添加处理能力，再提供给application层使用吗？

**Comment by wingsZz** [comment]
> 除了ios、android一些实现，BMF也有在鸿蒙下的适配计划。 这个需求是在library层添加处理能力，再提供给application层使用吗？

是的，打算实现一个底层跨平台的音视频处理库，再提供给应用层使用
