### ISSUE TITLE
Mac pip install BabitMF could not found error

### ISSUE THREAD

**Issue by 0xByteLeon** [BabitMF/bmf#109]
ERROR: Could not find a version that satisfies the requirement BabitMF (from versions: none)
ERROR: No matching distribution found for BabitMF

**Comment by 0xByteLeon** [comment]
Python version is 3.12, not compatibility，must  <= 3.10

**Comment by taoboyang** [comment]
You are right, for the reason that the macos python version has some compatibility issues with the ARM platform, BMF supports python 3.9 - 3.10 under the macOS ARM architecture and python 3.6 - 3.10 under the x86 architecture.
