### ISSUE TITLE
运行人脸检测demo时会一直打印：[info] *** dropping frame 7 at ts 3584。请问：dropping frame是什么意思？是检测时抽帧检测的吗？谢谢

### ISSUE THREAD

**Issue by QQiangren** [BabitMF/bmf#113]
我的代码如下：
import torch
import torch.nn.functional as F
import numpy as np
import sys
import time
import tensorrt as trt
import bmf.hml.hmp as mp
from nms import NMS
import PIL
from PIL import Image

def main():
    graph1 = graph({'dump_graph':1})

    video = graph1.decode({
        "input_path": "./face.mp4",
        #"video_params": {
        #    "hwaccel": "cuda",
        #}
    })["video"]

    video = video.module("trt_face_detect", {
        "model_path": "./version-RFB-640.engine",
        "label_to_frame": 1,
        "input_shapes": {
            "input": [1, 3, 480, 640]
        }}, entry="trt_face_detect.trt_face_detect")

    video = video.encode(
        None, {
            "output_path": "./trt_out.mp4",
            "video_params": {
                "codec": "h264_nvenc",
                "bit_rate": 5000000,
            }
        })

    video.run()
if __name__ == "__main__":
    main()

**Comment by sfeiwong** [comment]
这是编码（video.encode）时默认按照25 fps的帧率根据你的输入视频帧率来决定是否丢帧的策略。

**Comment by QQiangren** [comment]
麻烦请问编码时默认的25 fps帧率是否可以修改？在哪里可以设置。谢谢

**Comment by sfeiwong** [comment]
可以在encode的参数中配置：
"video_params": {
 "max_fr": 30
},
参考bmf文档：https://babitmf.github.io/docs/bmf/api/encode_module/

**Comment by QQiangren** [comment]
我在encode内设置了该参数，且执行程序时，看日志也生效了。有日志信息：
Output #0, mp4, to './trt_out.mp4':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 640x480, q=2-31, 5000 kb/s, 30 fps, 30 tbr, 17920 tbn, 35 tbc
我的输入视频的fps也是30。在输出视频也设置了"max_fr": 30。但是生成的视频帧率仍然是25。并且报*** dropping frame。

我的代码如下：
`def main():
    graph1 = graph({'dump_graph':1})

    video = graph1.decode({
        "input_path": "./face.mp4",
        "video_params": {
           "hwaccel": "cuda",
        }
    })["video"]

    video = video.module("trt_face_detect", {
        "model_path": "./version-RFB-640.engine",
        "input_shapes": {
            "input": [1, 3, 480, 640]
        }}, entry="trt_face_detect.trt_face_detect")

    video = video.module("face_postprocess",
        entry="face_postprocess.face_postprocess")

    video = video.encode(
        None, {
            "output_path": "./trt_out.mp4",
            "video_params": {
                "codec": "h264_nvenc",
                "bit_rate": 5000000,
                "g":"50",
                "bf": 0,
                "max_fr":30,
            }
        })

    video.run()
if __name__ == "__main__":
    main()
`

**Comment by QQiangren** [comment]
感谢指导，增加max_fr参数后，可以达到预期目标

**Comment by QQiangren** [comment]
邮件已经收到，我会尽快回复你。--任强强
