### ISSUE TITLE
ImportError: libavcodec.so.58: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wuxiaolianggit** [BabitMF/bmf#124]
您好，大佬，请教您一个，ImportError: libavcodec.so.58: cannot open shared object file: No such file or directory，但是我可以找到libavcodec.so.61，您知道怎么解决吗 @shining365 @mpr0xy @HuHeng @Jie-Fang @tongyuantongyu

**Comment by JackLau1222** [comment]
请描述一下 运行环境 用的哪个demo？ldd能查到此库吗

**Comment by wuxiaolianggit** [comment]
python 3.7   编译ffmpeg 7.0.1 版本  ldd 只能查到 libavcodec.so.61 => /usr/local/ffmpeg/lib/libavcodec.so.61 ，查看不到libavcodec.so.58

**Comment by JackLau1222** [comment]
本项目目前只兼容ffmpeg4-5 暂时不支持7

**Comment by wuxiaolianggit** [comment]
好的，大佬，了解了
