### ISSUE TITLE
windows平台编译后，python使用提示缺失c_ffmpeg_decoder模块

### ISSUE THREAD

**Issue by x850044053wwt** [BabitMF/bmf#131]
大佬们好

按照文档指引，我在windows平台上完成了编译。然后按照colab上的example 尝试执行https://colab.research.google.com/github/BabitMF/bmf/blob/master/bmf/demo/edit/bmf_edit_python.ipynb#scrollTo=vM3JZjmXHO-k

`# encode
(
    bmf.encode(concat_streams[0], concat_streams[1], {
        "output_path": output_path,
        "video_params": {
            "width": 1280,
            "height": 720,
            'codec': 'h264'
        }
    }).run()
)`

时我的python提示我

RuntimeError: ModuleNotFoundError: No module named 'c_ffmpeg_decoder'

请问下是哪里出了问题

**Comment by JackLau1222** [comment]
Have you downloaded the bmf package in Python？plz make sure the package you compiled is in the Python environment

**Comment by x850044053wwt** [comment]
由于网络原因，我无法在我的windows电脑上的python安装bmf。因此我是基于源码编译，然后在python中使用的。bmf包已经在我的python环境中，但是缺少了c_ffmpeg模块

**Comment by JackLau1222** [comment]
you can copy these complied files into your python environment. If you use conda, the path is ~/.conda/envs/<virtual_environment_name>/lib, and make sure the FFMPEG is enabled so that the c_ffmpeg_decoder can be built

**Comment by JackLau1222** [comment]
bmf_builtin_module.so(c_ffmpeg_decoder and other modules) is compiled and output in <project_root_directory>/output/bmf/lib, please check it

**Comment by x850044053wwt** [comment]
> bmf_builtin_module.so(c_ffmpeg_decoder and other modules) is compiled and output in <project_root_directory>/output/bmf/lib, please check it

我是windows平台编译，应该是bmf_builtin_module.dll这个lib吗，我没有找到
![Snipaste_2024-10-08_10-13-07](https://github.com/user-attachments/assets/c474c1ba-3a62-4e9d-967f-4c48c11f1ae9)

**Comment by JackLau1222** [comment]
> > bmf_builtin_module.so(c_ffmpeg_decoder and other modules) is compiled and output in <project_root_directory>/output/bmf/lib, please check it
> 
> 我是windows平台编译，应该是bmf_builtin_module.dll这个lib吗，我没有找到 ![Snipaste_2024-10-08_10-13-07](https://private-user-images.githubusercontent.com/47633686/374382577-c474c1ba-3a62-4e9d-967f-4c48c11f1ae9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTM5MDIsIm5iZiI6MTcyODM1MzYwMiwicGF0aCI6Ii80NzYzMzY4Ni8zNzQzODI1NzctYzQ3NGMxYmEtM2E2Mi00ZTlkLTk2N2YtNGM0OGMxMWYxYWU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAyMTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNTZjOTYwNTQ4ZTQzNjhjYjRiMjc3ZWYxZDVlYWM2MDcwYmU3MWE2OTJkODI4ZWRlMzdhYWI3NDhhZGM1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eI1_Ha84T2eh4C7GN3PUEFNd83GYBER6vdQ_7jgE0ZY)

yes, the c_ffmpeg_decoder module is built into bmf_builtin_module.dll, plz check log when you execute build.sh and make sure the BMF Summary contains FFMPEG_ENABLED          : ON

**Comment by x850044053wwt** [comment]
> > > bmf_builtin_module.so(c_ffmpeg_decoder and other modules) is compiled and output in <project_root_directory>/output/bmf/lib, please check it
> > 
> > 
> > 我是windows平台编译，应该是bmf_builtin_module.dll这个lib吗，我没有找到 ![Snipaste_2024-10-08_10-13-07](https://private-user-images.githubusercontent.com/47633686/374382577-c474c1ba-3a62-4e9d-967f-4c48c11f1ae9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTM5MDIsIm5iZiI6MTcyODM1MzYwMiwicGF0aCI6Ii80NzYzMzY4Ni8zNzQzODI1NzctYzQ3NGMxYmEtM2E2Mi00ZTlkLTk2N2YtNGM0OGMxMWYxYWU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAyMTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNTZjOTYwNTQ4ZTQzNjhjYjRiMjc3ZWYxZDVlYWM2MDcwYmU3MWE2OTJkODI4ZWRlMzdhYWI3NDhhZGM1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eI1_Ha84T2eh4C7GN3PUEFNd83GYBER6vdQ_7jgE0ZY)
> 
> yes, the c_ffmpeg_decoder module is built into bmf_builtin_module.dll, plz check log when you execute build.sh and make sure the BMF Summary contains FFMPEG_ENABLED : ON

是的，编译时summary是ON
![Snipaste_2024-10-08_10-19-44](https://github.com/user-attachments/assets/1c892b0e-896d-430c-b88b-a8bc0bd4c29e)

**Comment by JackLau1222** [comment]
> > > > bmf_builtin_module.so(c_ffmpeg_decoder and other modules) is compiled and output in <project_root_directory>/output/bmf/lib, please check it
> > > 
> > > 
> > > 我是windows平台编译，应该是bmf_builtin_module.dll这个lib吗，我没有找到 ![Snipaste_2024-10-08_10-13-07](https://private-user-images.githubusercontent.com/47633686/374382577-c474c1ba-3a62-4e9d-967f-4c48c11f1ae9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTM5MDIsIm5iZiI6MTcyODM1MzYwMiwicGF0aCI6Ii80NzYzMzY4Ni8zNzQzODI1NzctYzQ3NGMxYmEtM2E2Mi00ZTlkLTk2N2YtNGM0OGMxMWYxYWU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAyMTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNTZjOTYwNTQ4ZTQzNjhjYjRiMjc3ZWYxZDVlYWM2MDcwYmU3MWE2OTJkODI4ZWRlMzdhYWI3NDhhZGM1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eI1_Ha84T2eh4C7GN3PUEFNd83GYBER6vdQ_7jgE0ZY)
> > 
> > 
> > yes, the c_ffmpeg_decoder module is built into bmf_builtin_module.dll, plz check log when you execute build.sh and make sure the BMF Summary contains FFMPEG_ENABLED : ON
> 
> 是的，编译时summary是ON ![Snipaste_2024-10-08_10-19-44](https://private-user-images.githubusercontent.com/47633686/374383783-1c892b0e-896d-430c-b88b-a8bc0bd4c29e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTQzMDgsIm5iZiI6MTcyODM1NDAwOCwicGF0aCI6Ii80NzYzMzY4Ni8zNzQzODM3ODMtMWM4OTJiMGUtODk2ZC00MzBjLWI4OGItYThiYzBiZDRjMjllLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAyMjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmN2Q3NTNhZWQ5ZDZmOWNjYzRkNTExODBhNjY2OWM2MzE0ODY4ZDRkNzc4MDkxZWMyYTNmMzYyOWZlNTJjZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uDpIOI_sFUr5k-nbsqdcKrWruaV68uqlNxrSiNcVvs8)


OK, it seems that this is not the problem here. Please check whether libbuiltin_modules.so is built in the log.
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/5e605121-7ebe-4fd5-b7ca-90028dbf5e13">

**Comment by x850044053wwt** [comment]
> > > > > bmf_builtin_module.so(c_ffmpeg_decoder and other modules) is compiled and output in <project_root_directory>/output/bmf/lib, please check it
> > > > 
> > > > 
> > > > 我是windows平台编译，应该是bmf_builtin_module.dll这个lib吗，我没有找到 ![Snipaste_2024-10-08_10-13-07](https://private-user-images.githubusercontent.com/47633686/374382577-c474c1ba-3a62-4e9d-967f-4c48c11f1ae9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTM5MDIsIm5iZiI6MTcyODM1MzYwMiwicGF0aCI6Ii80NzYzMzY4Ni8zNzQzODI1NzctYzQ3NGMxYmEtM2E2Mi00ZTlkLTk2N2YtNGM0OGMxMWYxYWU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAyMTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNTZjOTYwNTQ4ZTQzNjhjYjRiMjc3ZWYxZDVlYWM2MDcwYmU3MWE2OTJkODI4ZWRlMzdhYWI3NDhhZGM1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eI1_Ha84T2eh4C7GN3PUEFNd83GYBER6vdQ_7jgE0ZY)
> > > 
> > > 
> > > yes, the c_ffmpeg_decoder module is built into bmf_builtin_module.dll, plz check log when you execute build.sh and make sure the BMF Summary contains FFMPEG_ENABLED : ON
> > 
> > 
> > 是的，编译时summary是ON ![Snipaste_2024-10-08_10-19-44](https://private-user-images.githubusercontent.com/47633686/374383783-1c892b0e-896d-430c-b88b-a8bc0bd4c29e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTQzMDgsIm5iZiI6MTcyODM1NDAwOCwicGF0aCI6Ii80NzYzMzY4Ni8zNzQzODM3ODMtMWM4OTJiMGUtODk2ZC00MzBjLWI4OGItYThiYzBiZDRjMjllLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAyMjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmN2Q3NTNhZWQ5ZDZmOWNjYzRkNTExODBhNjY2OWM2MzE0ODY4ZDRkNzc4MDkxZWMyYTNmMzYyOWZlNTJjZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uDpIOI_sFUr5k-nbsqdcKrWruaV68uqlNxrSiNcVvs8)
> 
> OK, it seems that this is not the problem here. Please check whether libbuiltin_modules.so is built in the log. <img alt="image" width="1200" src="https://private-user-images.githubusercontent.com/131463945/374391745-5e605121-7ebe-4fd5-b7ca-90028dbf5e13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTY4OTUsIm5iZiI6MTcyODM1NjU5NSwicGF0aCI6Ii8xMzE0NjM5NDUvMzc0MzkxNzQ1LTVlNjA1MTIxLTdlYmUtNGZkNS1iN2NhLTkwMDI4ZGJmNWUxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwMzAzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTJmNzczODQ2Y2RlNmM2ZTA1YjgzNGZlYzQxYTIzMTA1ODRjODVjM2IzZTI3ZDFjZTI1NTQ5MzIyNjQxYmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mOjSUpOn8h0k4g2NIG_eDD8HU552lx8BzECnu1vyM5Y">

我刚检查了编译过程，这个模块编译失败了，原因是用到了AVStream的codec成员，但是在我的ffmpeg5.1.2版本中，这个成员已经废弃了。这是否是一个bug

**Comment by JackLau1222** [comment]
> > > > > > bmf_builtin_module.so(c_ffmpeg_decoder and other modules) is compiled and output in <project_root_directory>/output/bmf/lib, please check it
> > > > > 
> > > > > 
> > > > > 我是windows平台编译，应该是bmf_builtin_module.dll这个lib吗，我没有找到 ![Snipaste_2024-10-08_10-13-07](https://private-user-images.githubusercontent.com/47633686/374382577-c474c1ba-3a62-4e9d-967f-4c48c11f1ae9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTM5MDIsIm5iZiI6MTcyODM1MzYwMiwicGF0aCI6Ii80NzYzMzY4Ni8zNzQzODI1NzctYzQ3NGMxYmEtM2E2Mi00ZTlkLTk2N2YtNGM0OGMxMWYxYWU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAyMTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNTZjOTYwNTQ4ZTQzNjhjYjRiMjc3ZWYxZDVlYWM2MDcwYmU3MWE2OTJkODI4ZWRlMzdhYWI3NDhhZGM1MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eI1_Ha84T2eh4C7GN3PUEFNd83GYBER6vdQ_7jgE0ZY)
> > > > 
> > > > 
> > > > yes, the c_ffmpeg_decoder module is built into bmf_builtin_module.dll, plz check log when you execute build.sh and make sure the BMF Summary contains FFMPEG_ENABLED : ON
> > > 
> > > 
> > > 是的，编译时summary是ON ![Snipaste_2024-10-08_10-19-44](https://private-user-images.githubusercontent.com/47633686/374383783-1c892b0e-896d-430c-b88b-a8bc0bd4c29e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTQzMDgsIm5iZiI6MTcyODM1NDAwOCwicGF0aCI6Ii80NzYzMzY4Ni8zNzQzODM3ODMtMWM4OTJiMGUtODk2ZC00MzBjLWI4OGItYThiYzBiZDRjMjllLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAyMjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmN2Q3NTNhZWQ5ZDZmOWNjYzRkNTExODBhNjY2OWM2MzE0ODY4ZDRkNzc4MDkxZWMyYTNmMzYyOWZlNTJjZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uDpIOI_sFUr5k-nbsqdcKrWruaV68uqlNxrSiNcVvs8)
> > 
> > 
> > OK, it seems that this is not the problem here. Please check whether libbuiltin_modules.so is built in the log. <img alt="image" width="1200" src="https://private-user-images.githubusercontent.com/131463945/374391745-5e605121-7ebe-4fd5-b7ca-90028dbf5e13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTY4OTUsIm5iZiI6MTcyODM1NjU5NSwicGF0aCI6Ii8xMzE0NjM5NDUvMzc0MzkxNzQ1LTVlNjA1MTIxLTdlYmUtNGZkNS1iN2NhLTkwMDI4ZGJmNWUxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwMzAzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTJmNzczODQ2Y2RlNmM2ZTA1YjgzNGZlYzQxYTIzMTA1ODRjODVjM2IzZTI3ZDFjZTI1NTQ5MzIyNjQxYmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mOjSUpOn8h0k4g2NIG_eDD8HU552lx8BzECnu1vyM5Y">
> 
> 我刚检查了编译过程，这个模块编译失败了，原因是用到了AVStream的codec成员，但是在我的ffmpeg5.1.2版本中，这个成员已经废弃了。这是否是一个bug

Good job! This seems to be a compatibility issue. We will fix this issue later. If you are interested, you are also welcome to submit a PR after the fix.
