### ISSUE TITLE
win上c++调用失败，python调用正常

### ISSUE THREAD

**Issue by x850044053wwt** [BabitMF/bmf#132]
hi 大佬们，如题所述。
![Snipaste_2024-10-09_12-00-09](https://github.com/user-attachments/assets/222230ed-f06f-42ee-8de3-2c5006d31778)

**Comment by x850044053wwt** [comment]
![image](https://github.com/user-attachments/assets/63d03bf3-7464-4a8d-940f-468be60fff06)
此处的hardcode是否影响了C++的调用

**Comment by sfeiwong** [comment]
module manager对模块管理的时候，会有一个默认path。 遇到了哪些相关问题？

**Comment by taoboyang** [comment]
Hi，确认下编译时是否 enable 了 ffmpeg，编译产物中是否有 builtin_module.dll （lib 文件夹）与 BUILTIN_CONFIG.json （根目录）这两个文件

**Comment by x850044053wwt** [comment]
> Hi，确认下编译时是否 enable 了 ffmpeg，编译产物中是否有 builtin_module.dll （lib 文件夹）与 BUILTIN_CONFIG.json （根目录）这两个文件

启用了ffmpeg，两个文件都存在。

**Comment by x850044053wwt** [comment]
> module manager对模块管理的时候，会有一个默认path。 遇到了哪些相关问题？

问题找到了，module manager会在exe路径和其上一级路径下寻找BUILTIN_CONFIG.json，同时在其中lib子文件夹下load builtin_module.dll。手动拷贝过去就可以正确运行了
