### ISSUE TITLE
FFMpegFilter

### ISSUE THREAD

**Issue by x850044053wwt** [BabitMF/bmf#149]
I added 3 ffmpeg filters, but there is only one filter node in the final dump result. Is it because optimize has optimized it out? Why is there only one filter left?

I encountered a problem where the speeds of 3 filters were inconsistent. The slow filter filled up the filter node queue, causing the fast filter to be blocked.

**Comment by sfeiwong** [comment]
Yes, filters will be merged into one filtergraph by default, but if you want them run by different nodes, it can be configured like this:
graph.set_option({'optimize_graph': False})

And please reference: bmf/demo/one_to_n_performance/one_to_n_transcode.py
