### ISSUE TITLE
Why is there no builtin_module in the compiled product on the Mac platform?

### ISSUE THREAD

**Issue by x850044053wwt** [BabitMF/bmf#152]
RT

**Comment by JackLau1222** [comment]
Please ensure the FFmpeg is enabled

**Comment by x850044053wwt** [comment]
> Please ensure the FFmpeg is enabled

FFmpeg is enabled，There is no such file in the github release resource either.

**Comment by JackLau1222** [comment]
> > Please ensure the FFmpeg is enabled
> 
> FFmpeg is enabled，There is no such file in the github release resource either.

Which compile script did you use? please use [build_osx.sh](https://github.com/BabitMF/bmf/blob/master/build_osx.sh) to build this project on macos. and you can refer to the [latest document version](https://github.com/BabitMF/BabitMF.github.io/pull/28). As for the package released by GitHub, it is obviously problematic. We will fix it as soon as possible.
