### ISSUE TITLE
Release for Mac Arm is incompatible

### ISSUE THREAD

**Issue by IdiosyncraticDragon** [BabitMF/bmf#156]
I have downloaded this :
<img width="915" alt="111" src="https://github.com/user-attachments/assets/ea5d2e42-3966-42b5-8cb2-e49bf3162ada">

and unzipped the file, modified the environment var in ~/.bashrc as
```bash
# for BabitMF, /Users/liguiying/installed/BabitMF
export C_INCLUDE_PATH=${C_INCLUDE_PATH}:/Users/liguiying/installed/BabitMF/bmf/include
export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:/Users/liguiying/installed/BabitMF/bmf/include
export LIBRARY_PATH=${LIBRARY_PATH}:/Users/liguiying/installed/BabitMF/bmf/lib
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/Users/liguiying/installed/BabitMF/bmf/lib

# only set if you want to use BMF in Python
export PYTHONPATH=${PYTHONPATH}:/Users/liguiying/installed/BabitMF/bmf/lib:/Users/liguiying/installed/BabitMF
```

However, when I import bmf, I met this error:
<img width="1278" alt="222" src="https://github.com/user-attachments/assets/016fc3b6-8ebb-4692-9b92-958d821fa4c3">
This seems like the Mac-arm release is incompatible with the ARM chip at all.

**Comment by JackLau1222** [comment]
Sorry about this. There are some problems in [this release](https://github.com/BabitMF/bmf/releases/download/v0.0.11/bmf-bin-macOS-arm64-cp39.tar.gz). For example, the product does not include builtin_module. We will solve this issue as soon as possible. In the meantime, could you use [version 0.09](https://github.com/BabitMF/bmf/releases/download/v0.0.9/bmf-bin-macOS-arm64-cp39.tar.gz) instead?

**Comment by IdiosyncraticDragon** [comment]
I tried, but it is still incompatible. Is there anything wrong in the arch of my Mac?
<img width="1273" alt="image" src="https://github.com/user-attachments/assets/274ea8c5-0474-4361-84f0-ed97ff84368e">

**Comment by IdiosyncraticDragon** [comment]
> I tried, but it is still incompatible. Is there anything wrong in the arch of my Mac? <img alt="image" width="1273" src="https://private-user-images.githubusercontent.com/3750460/394208751-274ea8c5-0474-4361-84f0-ed97ff84368e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MjI5NDksIm5iZiI6MTczMzgyMjY0OSwicGF0aCI6Ii8zNzUwNDYwLzM5NDIwODc1MS0yNzRlYThjNS0wNDc0LTQzNjEtODRmMC1lZDk3ZmY4NDM2OGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTBUMDkyNDA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmUwOTg3YTM4MmQ3NTczZjlmNmVmOGQ0OTAxNTYzMDZlM2Q0ZGRjOWIyNDExN2ViYmY3NjM3ODcwZjIxNjU1ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.t7OQlJ8NIXZuVoTvlGNhQgW0z5dbBMjsAwdLM5e0qjE">

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/25f92f17-b8db-4564-ac06-c6578a467ec9">

I found that the package tagged universal can be installed, but there is still a problem, which is another  issue#56 . 
```bash
Python 3.9.20 (main, Oct  3 2024, 02:27:54)
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bmf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liguiying/anaconda3/envs/bmf39/lib/python3.9/site-packages/bmf/__init__.py", line 4, in <module>
    from bmf.python_sdk.module_functor import make_sync_func
  File "/Users/liguiying/anaconda3/envs/bmf39/lib/python3.9/site-packages/bmf/python_sdk/__init__.py", line 1, in <module>
    from .module_functor import make_sync_func, ProcessDone
  File "/Users/liguiying/anaconda3/envs/bmf39/lib/python3.9/site-packages/bmf/python_sdk/module_functor.py", line 1, in <module>
    import bmf.lib._hmp
ImportError: dlopen(/Users/liguiying/anaconda3/envs/bmf39/lib/python3.9/site-packages/bmf/lib/_hmp.cpython-39-darwin.so, 0x0002): Library not loaded: @executable_path/../../../../Python
  Referenced from: <B92AC5A1-ADD4-3C93-A2AB-9483D9FA7C06> /Users/liguiying/anaconda3/envs/bmf39/lib/python3.9/site-packages/bmf/lib/_hmp.cpython-39-darwin.so
  Reason: tried: '/Users/liguiying/Python' (no such file), '/usr/local/lib/Python' (no such file), '/usr/lib/Python' (no such file, not in dyld cache)

```

**Comment by IdiosyncraticDragon** [comment]
I found there was a drawback in my enviroment: I used an X86_64 Anaconda on a M2 MacBook...... That's why I can not install arm whl and universal whl is OK. But the question #56 still exist, which makes the universal whl can not run functionally.

**Comment by IdiosyncraticDragon** [comment]
After reinstalling the arm version of Anaconda, the incompatible problem is fixed. I will close this issue.
