### ISSUE TITLE
wrong color space and range convert when filter graph use "format=rgba"

### ISSUE THREAD

**Issue by x850044053wwt** [BabitMF/bmf#161]
input yuv444p bt709 tv range，convert to rgba format，output rgba color looks fading
ffmpeg complain when calling `av_buffersrc_add_frame_flags` :
```
[src_0 @ 0000026ab60be580] Changing video frame properties on the fly is not supported by all filters.
[src_0 @ 0000026ab60be580] filter context - w: 1080 h: 1080 fmt: 0 csp: unknown range: unknown, incoming frame - w: 1080 h: 1080 fmt: 0 csp: bt709 range: tv pts_time: 0.000989583
```

**Comment by x850044053wwt** [comment]
![image](https://github.com/user-attachments/assets/32accb5a-2161-45d6-8d93-cdea26621372)
maybe input context unspecific color space and range

**Comment by JackLau1222** [comment]
Thanks for your feedback, we will check and fix it as soon as possible

**Comment by x850044053wwt** [comment]
After confirmation, this will not be a problem，encoder make result looks fading

`    nlohmann::json graph_para = {
        {"dump_graph", 0}
    };
    auto graph = bmf::builder::Graph(bmf::builder::NormalMode,
        bmf_sdk::JsonParam(graph_para));

   nlohmann::json decode_para = {
        {"input_path", "D:/work/bmf_example_files/big_bunny_10s_30fps.mp4"}
    };
    nlohmann::json enc_para = {
        {"output_path", "D:/Documents/Downloads/result.mp4"}
    };

    auto decoder = graph.Decode(bmf_sdk::JsonParam(decode_para));
    auto rgba = graph.FFMpegFilter({ decoder[0] }, "format", "rgba");
    graph.Encode(rgba[0], decoder["audio"], bmf_sdk::JsonParam(enc_para));
    graph.Run();`
result, first is raw image at 9s, second is yuv420p->rgba->yuv420p, they are not the same, Especially when the colors are bright
![image](https://github.com/user-attachments/assets/9963b5e4-3fcb-4ea7-a6b6-929d57e4938f)
![image](https://github.com/user-attachments/assets/c156d13e-8153-4c50-9d35-45d88aa16095)

**Comment by x850044053wwt** [comment]
before encoder, rgba Tensor is the same as raw. There is no problem when using ffmpeg cmd:
 `ffmpeg -i raw.mp4 -filter_complex "[0:v]format=rgba[rgba];[rgba]format=yuv420p[yuv420p]" -map "[yuv420p]" output.mp4`

**Comment by sfeiwong** [comment]
> before encoder, rgba Tensor is the same as raw. There is no problem when using ffmpeg cmd: `ffmpeg -i raw.mp4 -filter_complex "[0:v]format=rgba[rgba];[rgba]format=yuv420p[yuv420p]" -map "[yuv420p]" output.mp4`

So, do you mean it's still fading after BMF encoding? What's the csc range of the encoded video?

**Comment by x850044053wwt** [comment]
> > before encoder, rgba Tensor is the same as raw. There is no problem when using ffmpeg cmd: `ffmpeg -i raw.mp4 -filter_complex "[0:v]format=rgba[rgba];[rgba]format=yuv420p[yuv420p]" -map "[yuv420p]" output.mp4`
> 
> So, do you mean it's still fading after BMF encoding? What's the csc range of the encoded video?

yes, it still fading after BMF encoding. before encoding csc = CS_RGB, cr= CR_JPEG. However, changing rgb ColorModel property doesn't effect encoded video.
After discovering this problem, I simply made the above example to reflect this problem.

**Comment by x850044053wwt** [comment]
update debug result:
1、before encoder avcodec_send_frame，dump AVFrame to yuv binary，result shows Cr data offset is Wrong
2、get_filter_frame && [i0_0]scale=1080:1440,format=pix_fmts=yuv420p[o0_0] filter graph make Cr data wrong

**Comment by sfeiwong** [comment]
Could you please try bellow PR to verify whether the issue was resolved? 
https://github.com/BabitMF/bmf/pull/162

**Comment by HuHeng** [comment]
After some research, if you need to convert from RGB to YUV (BT.709), you need to explicitly specify the color space. You can use either the "format" filter of FFmpeg 7.1 or the "scale" filter with some parameters to do this.
