### ISSUE TITLE
images of docs/Page_*.md are mostly missing

### ISSUE THREAD

**Issue by kingalwayssunny** [BabitMF/bmf#38]
![image](https://github.com/BabitMF/bmf/assets/5424692/bd35215d-d7d9-4d1c-8bcf-6364c7c97004)

**Comment by taoboyang** [comment]
Thank you for your suggestion. You can refer to our official website for the latest documents about the project (https://babitmf.github.io/). We will also deal with the problems here.

**Comment by sfeiwong** [comment]
The latest documents were all targeted to https://babitmf.github.io/, some old docs in the source code repo were removed.
