### ISSUE TITLE
you said supported windows?

### ISSUE THREAD

**Issue by maxenergy** [BabitMF/bmf#43]
windows can't works,does it has branch for windows?

**Comment by frankfengw519** [comment]
Sorry, some of the windows related features are missing. We'll push the codes into maset branch later. Please stay tuned...

**Comment by wsy998** [comment]
> Sorry, some of the windows related features are missing. We'll push the codes into maset branch later. Please stay tuned...抱歉，缺少一些与 Windows 相关的功能。稍后我们会将代码推送到 maset 分支。敬请期待...

If the window is temporarily unavailable, then what about WSL?

**Comment by sfeiwong** [comment]
> 

It has been verified in Ubuntu/Debian, but not in terms of WSL. You can try it according to our install document, but Linux OS, vm or docker are recommanded.

**Comment by taoboyang** [comment]
> windows can't works,does it has branch for windows?

Hello, windows-related Features and compilation steps have been updated. You can pull the latest master branch code and refer to the document https://babitmf.github.io/docs/bmf/getting_started_yourself/install/#windows to compile and install.
