### ISSUE TITLE
python install error,It seems you didn't publish it

### ISSUE THREAD

**Issue by ProjetNice** [BabitMF/bmf#45]
ERROR: Could not find a version that satisfies the requirement BabitMF (from versions: none)
ERROR: No matching distribution found for BabitMF

**Comment by frankfengw519** [comment]
Could you please give a more detailed desciption of your development environment? What's the OS, hardware and the installation command you're using?

**Comment by frankfengw519** [comment]
Does the installation guide solve your problem? 
https://babitmf.github.io/docs/bmf/getting_started_yourself/install/

**Comment by ProjetNice** [comment]
Is there a communication group

**Comment by JackLau1222** [comment]
> Is there a communication group

https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=4cev1bee-4d94-42c8-972b-4ae4a12c9da1
you can view this feishu link in [issue#92](https://github.com/BabitMF/bmf/issues/92)
