### ISSUE TITLE
请问这个框架可以用来做avif图片编码吗？美学模型可以对图片打分吗？

### ISSUE THREAD

**Issue by wacdev** [BabitMF/bmf#53]
如题

**Comment by sfeiwong** [comment]
1. 需要确保环境中ffmpeg版本是5.1以上，可以做avif图片编码，替换bmf配置参数中，类似：
        bmf.encode(
            video['video'], None, {
                "output_path": “output.avif”,
                "format": "image2",
                "video_params": {
                    "codec": "libaom-av1",
                },
            }
2. 可以，美学模型本身是从图片训练给图片打分
