### ISSUE TITLE
fill_task_input don't consider the incomplete data ,  is it implied that the module must consider the incomplete data and carry out local caching and splicing processing when handling (TASK)? 

### ISSUE THREAD

**Issue by lxllsl** [BabitMF/bmf#85]
If a certain module (MODULE) requires multiple input streams (such as OVERLAY) to function normally, and only some of these input streams have data, is it implied that the module must consider the incomplete data and carry out local caching and splicing processing when handling (TASK)? Otherwise, there will be incomplete input data, leading to processing failure.

bool ImmediateInputStreamManager::fill_task_input(Task &task) {
        bool task_filled = false;
        for (auto & input_stream : input_streams_) {

            if (input_stream.second->is_empty()) {
                continue;
            }
            //one task cantain mult pkts, NEED add max pkts ctl?
            while (not input_stream.second->is_empty()) {
                Packet pkt = input_stream.second->pop_next_packet(false);
                if (pkt.timestamp() == BMF_EOF) {
                    if (input_stream.second->probed_) {
                        BMFLOG(BMF_INFO) << "immediate sync got EOF from dynamical update";
                        pkt.set_timestamp(DYN_EOS);
                        input_stream.second->probed_ = false;
                    } else
                        stream_done_[input_stream.first] = 1;
                }
                //READ：取到task的对应输入队列中
                task.fill_input_packet(input_stream.second->get_id(), pkt);
                task_filled = true;
            }
        }

**Comment by HuHeng** [comment]
```
If a certain module (MODULE) requires multiple input streams (such as OVERLAY) to function normally, and only some of these input streams have data, is it implied that the module must consider the incomplete data and carry out local caching and splicing processing when handling (TASK)?
```

------------------------------------------------------------------
Yes.
By default, the answer is yes. The default input mode for the BMF module is "immediate," which corresponds to the ImmediateInputStreamManager you mentioned. In the case of multiple inputs, there is no guarantee that each input will have packet data on every process call.
There is another inputmanager type called FramesyncInputStreamManager, which ensures that each input has packets. It may perform frame dropping or frame interpolation operations based on the timestamp of frame.
