### ISSUE TITLE
BMF提供了graph和pipeline的处理方式，这两者各自的特点是什么？使用场景有何不同？

### ISSUE THREAD

**Issue by steven-RD** [BabitMF/bmf#87]
###

**Comment by sfeiwong** [comment]
这里graph/pipeline是相似的含义，就是用户可以把各种原子能力通过框架以相互关联的方式构建起来调度运行的方式。 BMF大体上有两种区别较大的使用方式，1是graph mode，2是sync mode，这种方式是指用户直接通过bmf接口调用bmf模块的原子能力而不去构建graph，是单独调用模块能力的使用方式而没有使用引擎的多模块调度功能。
