### ISSUE TITLE
缺少sample

### ISSUE THREAD

**Issue by Hongyuan-Liu** [BabitMF/bmf#91]

**Comment by taoboyang** [comment]
您好，感谢您的关注！您提到的这个具象的场景目前确实是没有对应的 sample，不过您可以先参考一些我们已有的 demo 样例，https://github.com/BabitMF/bmf/tree/master/bmf/demo/gpu_module 这个 demo 展示了在 GPU 下做解码及一些图像处理的操作，此 demo 会对 GPU 的每个原子能力封装一个 BMF Module，；https://github.com/BabitMF/bmf/tree/master/bmf/demo/edit 这个 demo 尝试了 BMF Graph 多入多出的复杂处理能力，对于您的场景，你也可以尝试把每个原子化算法都实现为一个 BMF Module ，将这些 Module 串接起来完成您的需求
