### ISSUE TITLE
AttributeError: 'bmf.lib._bmf.sdk.Packet' object has no attribute 'get_data'

### ISSUE THREAD

**Issue by lxllsl** [BabitMF/bmf#93]
/usr/lib/python3.7/site-packages/bmf/modules/null_sink.py in process(self, task)
     21                 elif pkt.get_timestamp() != Timestamp.UNSET:
     22                     Log.log_node(LogLevel.DEBUG, task.get_node(),
---> 23                                  "process data", pkt.get_data(), 'time',
     24                                  pkt.get_timestamp())
     25         return ProcessResult.OK

AttributeError: 'bmf.lib._bmf.sdk.Packet' object has no attribute 'get_data'

**Comment by sfeiwong** [comment]
The interface should be outdated here, please try:
pkt.get_timestamp() -> pkt.timestamp
pkt.get_data() ->  pkt.get()

If it works, welcome to create a PR to fix. Thanks

**Comment by lxllsl** [comment]
pkt.get_timestamp() -> pkt.timestamp
pkt.get_data() -> pkt.get()

this work ，I will try fix it
